spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      name: gateway
      label: dev
      fail-fast: true
  application:
    name: gateway
  profiles:
    active: prod
