spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server.config-server.svc.cluster.local:80
      name: gateway
      label: main
      fail-fast: true
  profiles:
    active: prod
  # Redis 설정 (Config Server에서 오버라이드 가능)
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# 로깅 설정
logging:
  level:
    # Redis 관련 로깅
    PitterPetter.loventure.gateway.config.RedisConfig: INFO
    PitterPetter.loventure.gateway.config.RedisConnectionLogger: INFO
    PitterPetter.loventure.gateway.controller.RedisHealthController: INFO
    PitterPetter.loventure.gateway.service.RedisService: INFO
    
    # Spring Redis 로깅
    org.springframework.data.redis: INFO
    org.springframework.data.redis.connection: DEBUG
    org.springframework.data.redis.core: DEBUG
    
    # Lettuce 연결 풀 로깅
    io.lettuce.core: INFO
    
    # Gateway 전체 로깅
    PitterPetter.loventure.gateway: INFO
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
