spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server.config-server.svc.cluster.local:80
      name: gateway
      label: prod
      fail-fast: true
      search-paths:
        - '{application}'
  application:
    name: gateway
  profiles:
    active: prod
