spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server.config-server.svc.cluster.local:80
      name: gateway
      label: main
      fail-fast: true
  profiles:
    active: prod
